version: '3.8'

services:
  dockports:
    image: orsoman/dockports:latest
    container_name: dockports
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config
    environment:
      - DOCKPORTS_PORT=7577  # 可修改此端口以避免冲突
    restart: unless-stopped
